### PR TITLE
Windows side fixes for issue #86

### PR DESCRIPTION
**Pull request by russhaun**
fixed issues that were preventing artillery from starting on windows. reorganized code to take on new features. now is stable enough run. stiil have email issues to deal with been working with @corelanC0d3r to address any thing that might come up.

### CODE REVIEW

**Comment by russhaun** [comment]
hey @corelanc0d3r if IsUserAdmin function will only work on windows so it is already in the if is_widows group. hopefully that makes sense?

**Comment by corelanc0d3r** [comment]
sure, but if I read the code well, all calls to check_config() are now inside "if is_windows()"?

**Comment by russhaun** [comment]
Hey @corelanc0d3r here is a screen shot of the current artillery.py. as you can see there is a check_config() in the linux block. from the commit data it looks as if it is in windows section but it is not i did add it.

issue#86(linux_check_config)

**Comment by corelanc0d3r** [comment]
ok, should be good then :)

**Comment by russhaun** [comment]
hey @trustedsec .i am working on a new readme that includes updated info pertaining to file structure layout and also included windows values where appropriate. at this time i would also like to update the changelog and credits file to reflect changes since last update. I will wait until this is accepted unless ok'd upstream to apply those changes as well

**Comment by trustedsec** [comment]
Sounds good and appreciate the work on this. No issues at all.

**Pull request merged**
