### PR TITLE
Added feature to block entire class C network instead of individual IP

### PR DESCRIPTION
**Pull request by corelanc0d3r**
* Feature requires an additional setting in config `HONEYPOT_BAN_CLASSC="ON"`
* fixed some other bugs
* feature to block class C ranges seems to work well on my systems, but you may want to test if everything still works as intended if HONEYPOT_BAN_CLASSC is OFF

* Note: you may want to remove "config" from .gitignore again :)

### CODE REVIEW

**Comment by trustedsec** [comment]
Dude thanks man! Hope you are doing well Peter. -Dave

**Comment by corelanc0d3r** [comment]
:-) hope you're well too sir !

PS : you may want to remove "config" from .gitignore

**Comment by trustedsec** [comment]
All set and removed.

**Comment by trustedsec** [comment]
Thanks again :)

**Pull request merged**
