### PR TITLE
adding a parameter for silent install support, with automatic yes select

### PR DESCRIPTION
**Pull request by covelus**
adding a parameter for silent install support, with automatic yes option selection.
Now it can be run ./setup.py, as before, or ./setup.py -y, that means configuring 'yes' as answer to the prompted [y/n] questions. This is useful to automated deployment of artillery in, for example, cloud environments.
Thanks

### CODE REVIEW

**Comment by covelus** [comment]
Hello,
please, when you have time, check my PR, it is a very small contribution, and say to me if there's something to be changed :)
Thanks a lot

**Comment by russhaun** [comment]
hey whats up man. i contribute on the windows side of project. i downloaded your feature branch. it works except for one piece. when i go to uninstall i recieve a trace back it is as follows:

Traceback (most recent call last):
  File "C:\Users\russ\Downloads\artillery-feat-silent_install\setup.py", line 51, in <module>
    if (answer.lower() in ["yes", "y"]) or not interactive:
NameError: name 'answer' is not defined


I have also attached a screenshot for you to see what i mean. i go through all steps manually and with automatic option. manual install/uninstall works properly. also this is on windows 10/ python 3.6

artillery_silent_install

**Comment by russhaun** [comment]
update: 
            i added a small piece to your code and it now works as intended. the original function is as follows. note this is only for uninstall part.
#######original#######
        if os.path.isfile("C:\\Program Files (x86)\\Artillery\\artillery.py") and interactive:
            #print("[*] [*] If you would like to uninstall hit y then enter")
            answer = input("[*] Artillery detected. Do you want to uninstall [y/n:] ")
        #put this here to create loop
        if (answer.lower() in ["yes", "y"]) or not interactive:
            answer = "uninstall"

#########modified######
          if os.path.isfile("C:\\Program Files (x86)\\Artillery\\artillery.py") and interactive:
            #print("[*] [*] If you would like to uninstall hit y then enter")
            answer = input("[*] Artillery detected. Do you want to uninstall [y/n:] ")
        **else:
            answer = 'y'**
        #put this here to create loop
        if (answer.lower() in ["yes", "y"]) or not interactive:
            answer = "uninstall"

looking at above you can see i only added the else statement. it now properly installs/uninstalls manually and silent methods.

**Comment by covelus** [comment]
Thanks for the comment, I will try to take a look as soon as possible ;)

**Comment by russhaun** [comment]
update: 
          downloaded your branch after your patch. all looks good and works as expected.

tested on:
          ubuntu 18.04 with py 2.7.15
          windows 10 with py 3.6.2

i will add this to readme and changelog also but i will wait until this is accepted. I have made some changes to both regarding other pull requests.

**Comment by trustedsec** [comment]
Thanks for the work on this, looks great.

**Comment by covelus** [comment]
> Thanks for the work on this, looks great.

Thanks to you for the project, and for accepting my PR.
Cheers

**Pull request merged**
